export const quotes = [
    { author: `Albert Einstein`, text: `The most beautiful experience we can have is the mysterious. It is the fundamental emotion that stands at the cradle of true art and true science.` },
    { author: `Aldous Huxley`, text: `After silence, that which comes nearest to expressing the inexpressible is music.` },
    { author: `Alex Gaskarth`, text: `Life's greatest tragedy is not that it will someday end, but that most only live to follow directions and sometimes we end up totally lost.` },
    { author: `Anne Sexton`, text: `As it has been said: Love and a cough cannot be concealed. Even a small cough. Even a small love.` },
    { author: `Aristotle`, text: `The aim of art is to represent not the outward appearance of things, but their inward significance.` },
    { author: `Banksy`, text: `Art should comfort the disturbed and disturb the comfortable.` },
    { author: `Bill Hicks`, text: `A man on acid realized that all matter is merely energy condensed to a slow vibration, that we are all one consciousness experiencing itself subjectively, there is no such thing as death, life is only a dream, and we are the imagination of ourselves.` },
    { author: `Bill Hicks`, text: `It's all about money, not freedom. You think you're free? Try going somewhere without money.` },
    { author: `Bill Hicks`, text: `It's just a ride.` },
    { author: `Bill Hicks`, text: `Life is only a dream and we are the imagination of ourselves.` },
    { author: `Bill Hicks`, text: `Listen, the next revolution is gonna be a revolution of ideas.` },
    { author: `Bob Marley`, text: `None but ourselves can free our minds.` },
    { author: `Brian Tracy`, text: `It doesn't matter where you are coming from. All that matters is where you are going.` },
    { author: `Captain Disillusion`, text: `Love with your heart; use your head for everything else.` },
    { author: `Charles Bukowski`, text: `Poetry is what happens when nothing else can.` },
    { author: `Chuck Palahniuk`, text: `Losing all hope was freedom.` },
    { author: `Clive Barker`, text: `Any fool can be happy. It takes a man with real heart to make beauty out of the stuff that makes us weep.` },
    { author: `Confucius`, text: `Music produces a kind of pleasure which human nature cannot do without.` },
    { author: `Dmitri Shostakovich`, text: `When a man is in despair, it means that he still believes in something.` },
    { author: `E. E. Cummings`, text: `To be nobody but yourself in a world which is doing its best day and night to make you like everybody else means to fight the hardest battle which any human being can fight and never stop fighting.` },
    { author: `Flannery O'Connor`, text: `Art never responds to the wish to make it democratic; it is not for everybody; it is only for those who are willing to undergo the effort needed to understand it.` },
    { author: `Frank Zappa`, text: `Without deviation from the norm, progress is not possible.` },
    { author: `Frederick Delius`, text: `Music is an outburst of the soul.` },
    { author: `Friedrich Nietzsche`, text: `And those who were seen dancing were thought to be insane by those who could not hear the music.` },
    { author: `Friedrich Nietzsche`, text: `We have art in order not to die of the truth.` },
    { author: `Friedrich Nietzsche`, text: `Without music, life would be a mistake.` },
    { author: `Friedrich Nietzsche`, text: `You must have chaos within you to give birth to a dancing star.` },
    { author: `G-Eazy`, text: `It all depends on what you value. Figure this out on your own, nobody shows you how to.` },
    { author: `George Bernard Shaw`, text: `Without art, the crudeness of reality would make the world unbearable.` },
    { author: `George Eliot`, text: `Life seems to go on without effort when I am filled with music.` },
    { author: `Gerard Way`, text: `Would you destroy something perfect in order to make it beautiful?` },
    { author: `Heinrich Heine`, text: `Where words leave off, music begins.` },
    { author: `Henri Matisse`, text: `Creativity takes courage.` },
    { author: `Henry Wadsworth Longfellow`, text: `Music is the universal language of mankind.` },
    { author: `Joss Whedon`, text: `All worthy work is open to interpretations the author did not intend. Art isn't your pet - it's your kid. It grows up and talks back to you.` },
    { author: `Leonardo da Vinci`, text: `The noblest pleasure is the joy of understanding.` },
    { author: `Leopold Stokowski`, text: `A painter paints pictures on canvas. But musicians paint their pictures on silence.` },
    { author: `Maria Cristina Mena`, text: `The pianokeys are black and white, but they sound like a million colors in your mind.` },
    { author: `Maria von Trapp`, text: `Music acts like a magic key, to which the most tightly closed heart opens.` },
    { author: `Marilyn Manson`, text: `Music is the strongest form of magic.` },
    { author: `Maya Angelou`, text: `Everything in the universe has a rhythm, everything dances.` },
    { author: `Pablo Picasso`, text: `Art is the lie that enables us to realize the truth.` },
    { author: `Pablo Picasso`, text: `Art washes away from the soul the dust of everyday life.` },
    { author: `Pablo Picasso`, text: `Every child is an artist. The problem is how to remain an artist once he grows up.` },
    { author: `Pablo Picasso`, text: `Everything you can imagine is real.` },
    { author: `Pablo Picasso`, text: `Only put off until tomorrow what you are willing to die having left undone.` },
    { author: `Prince`, text: `Hard to say what's right when all I wanna do is wrong.` },
    { author: `Rick Riordan`, text: `You might as well ask an artist to explain his art, or ask a poet to explain his poem. It defeats the purpose. The meaning is only clear thorough the search.` },
    { author: `Robert Frost`, text: `Forgive, O Lord, my little jokes on Thee. And I'll forgive Thy great big one on me.` },
    { author: `Sarah Williams`, text: `Though my soul may set in darkness, it will rise in perfect light; I have loved the stars too fondly to be fearful of the night.` },
    { author: `SPARTALIEN`, text: `Remember, that times and situations change, but your heart doesn't have to necessarily.` },
    { author: `Stella Adler`, text: `Life beats down and crushes the soul and art reminds you that you have one.` },
    { author: `The Narrator of The Stanley Parable`, text: `Perhaps his goal had not been to understand, but to let go.` },
    { author: `Timothy Leary`, text: `...as a guide and protection. Trust your divinity, trust your brain.` },
    { author: `Timothy Leary`, text: `The goals of an intelligent life, according to Socrates, is to pursue the philosophic quest - to increase one's knowledge of self and world.` },
    { author: `Timothy Leary`, text: `The universe is an intelligence test.` },
    { author: `Timothy Leary`, text: `Think for yourself. Question authority.` },
    { author: `Tom Petty`, text: `Excuse me if I have some place in my mind where I go time to time.` },
    { author: `Tom Waits`, text: `I like beautiful melodies telling me terrible things.` },
    { author: `Tupac Shakur`, text: `People tend to choke that which they do not understand.` },
    { author: `Tupac Shakur`, text: `Reality is wrong. Dreams are for the real.` },
    { author: `Victor Hugo`, text: `Music expresses that which cannot be put into words and that which cannot remain silent.` },
    // TODO: { author: `Busta`, text: `Sip slow make it last` },
]
